### ISSUE TITLE
help on building

### ISSUE THREAD

**Issue by ghost** [CraftSpider/GCDecompiler#5]
building this is an absolute pain in the backside, if you could, please release a built version as that would help me greatly, also how do i recompile?

**Comment by CraftSpider** [comment]
Apologies for the delay in response, I have finals exams soon and am very busy.

1) Appveyor captures artifacts for 6 months after the build for linux, I'll add windows to it. Once I get to a 'release' point I'll make repo tags with attached builds.
2) Currently, as this whole program is very alpha, it doesn't support recompilation, sorry. I'll look into adding it at some point, but it's kind of a secondary goal.

**Comment by ghost** [comment]
Ah very cool! thank you for updating me on the situation, i thought you had gone somewhere or somehting because nothing had been updated in quite some time. Also about the finals, understandable have a great day.

**Comment by ghost** [comment]
yay your back!!!! cant wait tos ee what you do with this :)))

**Comment by CraftSpider** [comment]
There's a lot of work, and I still have other projects, but I was inspired to try to get this thing at least back to its 'peak point' functionality

**Comment by ghost** [comment]
Of course, for a project like this there is a lot of things to do. I've been furthering my C++ skills if you need any help or anything like that, do you have discord by any chance?

**Comment by CraftSpider** [comment]
I do have a discord, it's under the same username as my github, discrim `#0001`

**Comment by ghost** [comment]
Added :)
